version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-q',
          '-d',
          'postgres',
          '-U',
          'postgres'
        ]
      timeout: 35s
      interval: 10s
      retries: 10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
      - POSTGRES_DB = ${POSTGRES_DB}

    networks:
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${PWD}/pg_dump.sql:/docker-entrypoint-initdb.d/pg_dump.sql

volumes:
  pgdata:
networks:
  webnet:
